# Raster Based Annual Summaries

This notebook demonstrates how the per water body summaries are generated for a single tile.

In [1]:
%load_ext water_quality.magics

If running this notebook on the DEV Analysis Sandbox, and seeking to use the waterbodies DEV database, save the required credentials in the `.env` file at `/home/jovyan/.env` and load the credentials using the cell below.

In [2]:
from dotenv import load_dotenv
load_dotenv("/home/jovyan/.env", verbose=True, override=True)

True

If using the DEV waterbodies database, ignore the cell below. If looking to use a file based database, use the cell magic command `%%ignore` to ignore the above cell.

In [3]:
%%ignore
import os
# This ensures the database is a sqlite file database
os.environ["TestingMode"] = "True"
bool(os.environ.get("TestingMode", None))

## Getting started

### Load required python packages

In [4]:
import gc
import json
import logging
import sys

import click
import dask
import numpy as np
import pandas as pd
import rioxarray
import xarray as xr
from datacube import Datacube
from waterbodies.db import get_waterbodies_engine

from water_quality.io import check_directory_exists, get_filesystem, join_url
from water_quality.logs import setup_logging
from water_quality.summaries.summary import (
    REQUIRED_COLUMNS,
    add_water_quality_observations_to_db,
    check_obs_ids,
)
from water_quality.tasks import split_tasks

### Define analysis parameters

- `raster_processing_tasks`: a text file containing a list of the DE Africa Waterbodies Historical Extent COGs to be processed.
- `waterbodies_to_exclude`: a json file containing a mapping of waterbodies uids and their corresponding historical extent COGs that cover multiple tiles. The waterbodies in this file will be excluded from the raster based processing of the water quality annual summaries and instead will be processed separately using the vector based processing tool.
- `max_parallel_steps`: The total number of parallel workers or pods expected in the workflow. This value is used to divide the list of tasks to be processed among the available workers.
- `worker_idx`: The sequential index (0-indexed) of the current worker. This index determines which subset of tasks the current worker will process.
- `overwrite`: If overwrite is True tasks that have already been processed will be rerun.

In [5]:
raster_processing_tasks="../../src/water_quality/data/raster_processing_tasks.txt"
waterbodies_to_exclude="../../src/water_quality/data/vector_processing_tasks.json"
max_parallel_steps=1
worker_idx=0
overwrite=True
log="INFO"

## Process raster tasks

In [6]:
log_level = getattr(logging, log.upper())
_log = setup_logging(log_level)

In [7]:
fs = get_filesystem(waterbodies_to_exclude, anon=False)
with fs.open(waterbodies_to_exclude, "r") as file:
    uids_to_exclude = list(json.load(file).keys())

In [8]:
fs = get_filesystem(raster_processing_tasks, anon=False)
with fs.open(raster_processing_tasks, "r") as file:
    all_tasks = file.read().splitlines()

In [9]:
tasks_to_run = split_tasks(all_tasks, max_parallel_steps, worker_idx)

if not tasks_to_run:
    _log.warning(f"Worker {worker_idx} has no tasks to process. Exiting.")
    sys.exit(0)

_log.info(f"Worker {worker_idx} processing {len(tasks_to_run)} tasks")

2026-03-22 11:37:17,177 __main__ [INFO]: Worker 0 processing 2779 tasks

In [10]:
dc = Datacube(app="process_raster_tasks")
measurements = [
    "fai",
    "ndvi",
    "hue",
    "owt",
    "chla",
    "tsi",
    "tsm",
    "st_max",
    "st_median",
    "st_min",
    "water_mask",
]
product = "wq_annual"
dask_chunks = {"x": 3200, "y": 3200}
quantiles = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]

2026-03-22 11:37:17,272 alembic.runtime.plugins [INFO]: setup plugin alembic.autogenerate.schemas
2026-03-22 11:37:17,272 alembic.runtime.plugins [INFO]: setup plugin alembic.autogenerate.tables
2026-03-22 11:37:17,273 alembic.runtime.plugins [INFO]: setup plugin alembic.autogenerate.types
2026-03-22 11:37:17,273 alembic.runtime.plugins [INFO]: setup plugin alembic.autogenerate.constraints
2026-03-22 11:37:17,273 alembic.runtime.plugins [INFO]: setup plugin alembic.autogenerate.defaults
2026-03-22 11:37:17,273 alembic.runtime.plugins [INFO]: setup plugin alembic.autogenerate.comments

In [11]:
engine = get_waterbodies_engine()

Check which database is in use.

In [12]:
engine.url

postgresql+psycopg2://waterbodies_writer:***@db-reader:5432/waterbodies

Select the historical extent COG file to process.

In [28]:
cog_path = 's3://deafrica-water-quality-dev/historical-extent-rasters/historical_extent_x208y056.tif'

In [29]:
assert cog_path in all_tasks

In [30]:
extent_da = rioxarray.open_rasterio(cog_path).squeeze()
extent_da

<xarray.DataArray (y: 9600, x: 9600)> Size: 737MB
[92160000 values with dtype=int64]
Coordinates:
  * y            (y) float64 77kB -1.92e+06 -1.92e+06 ... -2.016e+06 -2.016e+06
  * x            (x) float64 77kB 2.592e+06 2.592e+06 ... 2.688e+06 2.688e+06
    band         int64 8B 1
    spatial_ref  int64 8B 0
Attributes:
    WB_ID_to_UID:   {"301651": "kt5ph2c850", "301845": "kt5q3jteu1", "302158"...
    AREA_OR_POINT:  Area
    _FillValue:     0
    scale_factor:   1.0
    add_offset:     0.0

In [31]:
# During rasterization of the historical extent COGs, the nodata
# value was set to 0. The processing makes the assumption that this
# is maintained. If this assumption is violated, summaries produced
# will be incorrect.
nodata_val = 0
assert nodata_val == extent_da.odc.nodata

Select which waterbodies to be processed. Waterbodies that are covered by more than 1 historical extent raster are exlcuded and will be processed using the vector processing tool.

In [32]:
wb_id_to_uid = {
    int(wb_id): uid
    for wb_id, uid in json.loads(
        extent_da.attrs["WB_ID_to_UID"]
    ).items()
}
wb_ids_to_exclude = [
    wb_id
    for wb_id, uid in wb_id_to_uid.items()
    if uid in uids_to_exclude
]
wb_id_to_uid_filtered = {
    wb_id: uid
    for wb_id, uid in wb_id_to_uid.items()
    if wb_id not in wb_ids_to_exclude
}

assert len(wb_id_to_uid_filtered) == len(wb_id_to_uid) - len(
    wb_ids_to_exclude
)

wb_ids_to_keep = list(wb_id_to_uid_filtered.keys())

wb_ids_to_keep[:5]

[301651, 301845, 302158, 302159, 302160]

In [33]:
if len(wb_ids_to_keep) > 0:
    extent_da = extent_da.where(
        extent_da.isin(wb_ids_to_keep), other=nodata_val
    )
else:
    _log.info(
        "No waterbodies for raster processing in this COG after filtering. "
        "Skipping processing for this historical extent COG file."
    )
    pass

In [34]:
extent_da = extent_da.where(extent_da != nodata_val).astype(
    np.float32
)
extent_da

<xarray.DataArray (y: 9600, x: 9600)> Size: 369MB
array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]],
      shape=(9600, 9600), dtype=float32)
Coordinates:
  * y            (y) float64 77kB -1.92e+06 -1.92e+06 ... -2.016e+06 -2.016e+06
  * x            (x) float64 77kB 2.592e+06 2.592e+06 ... 2.688e+06 2.688e+06
    band         int64 8B 1
    spatial_ref  int64 8B 0
Attributes:
    WB_ID_to_UID:   {"301651": "kt5ph2c850", "301845": "kt5q3jteu1", "302158"...
    AREA_OR_POINT:  Area
    _FillValue:     0
    scale_factor:   1.0
    add_offset:     0.0

In [35]:
# Load all years of data available
ds = dc.load(
    product=product,
    like=extent_da.odc.geobox,
    measurements=measurements,
    dask_chunks=dask_chunks,
)

# Mask the data to only include pixels for waterbodies to be procesed
ds = ds.where(extent_da)
ds

<xarray.Dataset> Size: 105GB
Dimensions:     (time: 26, y: 9600, x: 9600)
Coordinates:
  * time        (time) datetime64[ns] 208B 2000-07-01T23:59:59.999999 ... 202...
  * y           (y) float64 77kB -1.92e+06 -1.92e+06 ... -2.016e+06 -2.016e+06
  * x           (x) float64 77kB 2.592e+06 2.592e+06 ... 2.688e+06 2.688e+06
    band        int64 8B 1
Data variables:
    fai         (time, y, x) float32 10GB dask.array<chunksize=(1, 3200, 3200), meta=np.ndarray>
    ndvi        (time, y, x) float32 10GB dask.array<chunksize=(1, 3200, 3200), meta=np.ndarray>
    hue         (time, y, x) float32 10GB dask.array<chunksize=(1, 3200, 3200), meta=np.ndarray>
    owt         (time, y, x) float32 10GB dask.array<chunksize=(1, 3200, 3200), meta=np.ndarray>
    chla        (time, y, x) float32 10GB dask.array<chunksize=(1, 3200, 3200), meta=np.ndarray>
    tsi         (time, y, x) float32 10GB dask.array<chunksize=(1, 3200, 3200), meta=np.ndarray>
    tsm         (time, y, x) float32 10GB dask.array<chunksize=(1, 3200, 3200), meta=np.ndarray>
    st_max      (time, y, x) float32 10GB dask.array<chunksize=(1, 3200, 3200), meta=np.ndarray>
    st_median   (time, y, x) float32 10GB dask.array<chunksize=(1, 3200, 3200), meta=np.ndarray>
    st_min      (time, y, x) float32 10GB dask.array<chunksize=(1, 3200, 3200), meta=np.ndarray>
    water_mask  (time, y, x) float32 10GB dask.array<chunksize=(1, 3200, 3200), meta=np.ndarray>
Attributes:
    crs:           PROJCS["WGS 84 / NSIDC EASE-Grid 2.0 Global",GEOGCS["WGS 8...
    grid_mapping:  spatial_ref

In [36]:
# Edge case: If no wq_annual data is available for the historical extent COG
if len(list(ds.data_vars)) == 0:
    _log.info(
        f"No {product} data available for any year for this historical extent COG. "
        "Skipping processing for this historical extent COG file."
    )
    pass

Using the waterbodies uids check the database to find water quality observations that already exist.

In [37]:
years = [
    pd.Timestamp(year).strftime("%Y/%m/%d")
    for year in ds.time.values
]
waterbody_uids = list(wb_id_to_uid_filtered.values())

possible_obs_ids = [
    f"{year}_{waterbody_uid}"
    for year in years
    for waterbody_uid in waterbody_uids
]
existing_obs_ids = check_obs_ids(possible_obs_ids, engine)

if overwrite:
    obs_ids = set(existing_obs_ids).union(
        set(possible_obs_ids) - set(existing_obs_ids)
    )
else:
    obs_ids = set(possible_obs_ids) - set(existing_obs_ids)

obs_ids = sorted(list(obs_ids))

obs_ids[:3]

['2000/07/01_kt5jeey165', '2000/07/01_kt5jp6df4t', '2000/07/01_kt5jpgzy0q']

In [38]:
if not obs_ids:
    _log.info(
        "All possible water quality observations for waterbodies in this historical "
        "extent COG file already exist in the database and overwrite is set to False. "
        "Skipping processing for this historical extent COG file."
    )
    pass

In [39]:
_log.info(
    f"Processing per waterbody statistics for {ds.time.size} years for "
    f"{len(wb_id_to_uid_filtered)} waterbodies ..."
)
df_drop_columns = ["band", "spatial_ref"]

2026-03-22 11:39:43,595 __main__ [INFO]: Processing per waterbody statistics for 26 years for 1758 waterbodies ...

In [25]:
from deafrica_tools.dask import create_local_dask_cluster

In [26]:
create_local_dask_cluster()

2026-03-22 11:37:24,473 distributed.scheduler [INFO]: State start
2026-03-22 11:37:24,475 distributed.diskutils [INFO]: Found stale lock file and directory '/tmp/dask-scratch-space/scheduler-9pcwf09m', purging
2026-03-22 11:37:24,475 distributed.diskutils [INFO]: Found stale lock file and directory '/tmp/dask-scratch-space/worker-61upzocm', purging
2026-03-22 11:37:24,478 distributed.scheduler [INFO]:   Scheduler at:     tcp://127.0.0.1:40501
2026-03-22 11:37:24,478 distributed.scheduler [INFO]:   dashboard at:  /user/victoria@kartoza.com/proxy/8787/status
2026-03-22 11:37:24,479 distributed.scheduler [INFO]: Registering Worker plugin shuffle
2026-03-22 11:37:24,484 distributed.nanny [INFO]:         Start Nanny at: 'tcp://127.0.0.1:46559'
2026-03-22 11:37:24,881 distributed.scheduler [INFO]: Register worker addr: tcp://127.0.0.1:46505 name: 0
2026-03-22 11:37:24,890 distributed.scheduler [INFO]: Starting worker compute stream, tcp://127.0.0.1:46505
2026-03-22 11:37:24,890 distributed.core [INFO]: Starting established connection to tcp://127.0.0.1:48678
2026-03-22 11:37:24,895 distributed.scheduler [INFO]: Receive client connection: Client-7ecdc02e-25e3-11f1-8bc9-bee21980e0a0
2026-03-22 11:37:24,895 distributed.core [INFO]: Starting established connection to tcp://127.0.0.1:48688
2026-03-22 11:37:24,903 distributed.scheduler [INFO]: Registering Worker plugin _WorkerSetupPlugin-828b7333-3bb1-447b-af34-a65a7fa66ca1

2026-03-22 11:37:43,720 distributed.core [INFO]: Event loop was unresponsive in Nanny for 7.45s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2026-03-22 11:37:43,720 distributed.core [INFO]: Event loop was unresponsive in Scheduler for 7.45s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
BokehUserWarning: reference already known 'p1011'
BokehUserWarning: reference already known 'p1051'
BokehUserWarning: reference already known 'p1289'
BokehUserWarning: reference already known 'p1295'
BokehUserWarning: reference already known 'p1361'
2026-03-22 11:38:08,966 distributed.core [INFO]: Event loop was unresponsive in Nanny for 8.80s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2026-03-22 11:38:08,967 distributed.core [INFO]: Event loop was unresponsive in Scheduler for 8.80s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2026-03-22 11:38:27,970 distributed.core [INFO]: Event loop was unresponsive in Scheduler for 6.65s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2026-03-22 11:38:31,831 distributed.core [INFO]: Event loop was unresponsive in Nanny for 8.56s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2026-03-22 11:38:31,833 distributed.core [INFO]: Event loop was unresponsive in Scheduler for 3.86s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2026-03-22 11:40:08,190 distributed.core [INFO]: Event loop was unresponsive in Nanny for 8.61s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2026-03-22 11:40:08,191 distributed.core [INFO]: Event loop was unresponsive in Scheduler for 8.61s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2026-03-22 11:40:30,769 distributed.core [INFO]: Event loop was unresponsive in Nanny for 9.39s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2026-03-22 11:40:30,773 distributed.core [INFO]: Event loop was unresponsive in Scheduler for 7.44s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2026-03-22 11:40:52,060 distributed.core [INFO]: Event loop was unresponsive in Nanny for 6.71s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2026-03-22 11:40:54,812 distributed.core [INFO]: Event loop was unresponsive in Scheduler for 9.45s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2026-03-22 11:40:55,865 distributed.core [INFO]: Event loop was unresponsive in Nanny for 3.80s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2026-03-22 11:41:03,285 distributed.core [INFO]: Event loop was unresponsive in Nanny for 3.62s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2026-03-22 11:41:03,286 distributed.core [INFO]: Event loop was unresponsive in Scheduler for 3.62s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.

In [40]:
_log.info(
    "Processing water area consistently indicating algae ..."
)
water_mask_count = (
    ds["water_mask"]
    .notnull()
    .groupby(extent_da)
    .sum(dim=("x", "y"))
)
fai_count = (
    ds["fai"].notnull().groupby(extent_da).sum(dim=("x", "y"))
)
ndvi_count = (
    ds["ndvi"].notnull().groupby(extent_da).sum(dim=("x", "y"))
)

water_mask_count, fai_count, ndvi_count = dask.compute(
    water_mask_count, fai_count, ndvi_count
)

2026-03-22 11:39:48,283 __main__ [INFO]: Processing water area consistently indicating algae ...
/opt/venv/lib/python3.12/site-packages/distributed/client.py:3371: UserWarning: Sending large graph of size 2.32 GiB.
This may cause some slowdown.
Consider loading the data with Dask directly
 or using futures or delayed objects to embed the data into the graph without repetition.
See also https://docs.dask.org/en/stable/best-practices.html#load-data-with-dask for more information.
  warnings.warn(
2026-03-22 11:41:08,793 - distributed.worker - ERROR - Compute Failed
Key:       ('shuffle-split-1071274a21bf11ecf8994cfd1f1dc36a', 355)
State:     executing
Task:  <Task ('shuffle-split-1071274a21bf11ecf8994cfd1f1dc36a', 355) _getitem(...)>
Exception: "ValueError('Array chunk size or shape is unknown. Possible solution with x.compute_chunk_sizes()')"
Traceback: '  File "/opt/venv/lib/python3.12/site-packages/dask/array/_shuffle.py", line 313, in _getitem\n    return getitem(obj, index[1])\n           ^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/venv/lib/python3.12/site-packages/dask/array/chunk.py", line 423, in getitem\n    raise ValueError(\n'

2026-03-22 11:41:08,798 - distributed.worker - ERROR - Compute Failed
Key:       ('shuffle-split-1071274a21bf11ecf8994cfd1f1dc36a', 299)
State:     executing
Task:  <Task ('shuffle-split-1071274a21bf11ecf8994cfd1f1dc36a', 299) _getitem(...)>
Exception: "ValueError('Array chunk size or shape is unknown. Possible solution with x.compute_chunk_sizes()')"
Traceback: '  File "/opt/venv/lib/python3.12/site-packages/dask/array/_shuffle.py", line 313, in _getitem\n    return getitem(obj, index[1])\n           ^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/venv/lib/python3.12/site-packages/dask/array/chunk.py", line 423, in getitem\n    raise ValueError(\n'

ValueError: Array chunk size or shape is unknown. Possible solution with x.compute_chunk_sizes()

In [ ]:
fai_cover = (
    fai_count / water_mask_count.where(water_mask_count > 0)
) * 100

fai_cover_df = fai_cover.to_dataframe(name="fai_cover").drop(
    columns=df_drop_columns
)
del fai_cover
gc.collect()

fai_cover_df

In [26]:
_log.info(
    "Processing water area consistently indicating vegetation ..."
)
ndvi_count = (~ds["ndvi"].isnull()).groupby(extent_da).sum()
ndvi_cover = (
    ndvi_count / water_mask_count.where(water_mask_count > 0)
) * 100

ndvi_cover_df = ndvi_cover.to_dataframe(name="ndvi_cover").drop(
    columns=df_drop_columns
)
ndvi_cover_df

2026-03-13 20:16:07,837 __main__ [INFO]: Processing water area consistently indicating vegetation ...

                                     ndvi_cover
time                       group
2000-07-01 23:59:59.999999 379743.0         NaN
                           380010.0         NaN
                           380011.0       100.0
                           380012.0         NaN
                           380023.0         NaN
...                                         ...
2024-07-01 23:59:59.999999 380111.0       100.0
                           380112.0       100.0
                           380113.0       100.0
                           380114.0       100.0
                           380115.0       100.0

[2275 rows x 1 columns]

In [27]:
annual_quantile_measurements = [
    "hue",
    "owt",
    "chla",
    "tsi",
    "tsm",
    "st_max",
    "st_median",
    "st_min",
]
# Sanity check
assert set(annual_quantile_measurements).issubset(
    set(measurements)
)
assert set(annual_quantile_measurements).issubset(
    set(list(ds.data_vars))
)

In [28]:
quantiles_df_to_merge = []
for measurement in annual_quantile_measurements:
    _log.info(
        f"Processing per waterbody quantiles for the {measurement} variable"
    )
    with xr.set_options(use_flox=False):
        quantiles_da = (
            ds[measurement].groupby(extent_da).quantile(quantiles)
        )
    quantiles_df = quantiles_da.to_dataframe().unstack("quantile")
    quantiles_df.columns = [
        f"{measurement}_q{q}".replace(".", "_")
        for _, q in quantiles_df.columns
    ]
    quantiles_df_to_merge.append(quantiles_df)

2026-03-13 20:16:59,470 __main__ [INFO]: Processing per waterbody quantiles for the hue variable
2026-03-13 20:18:18,687 __main__ [INFO]: Processing per waterbody quantiles for the owt variable
2026-03-13 20:19:27,732 __main__ [INFO]: Processing per waterbody quantiles for the chla variable
2026-03-13 20:20:37,332 __main__ [INFO]: Processing per waterbody quantiles for the tsi variable
2026-03-13 20:21:47,430 __main__ [INFO]: Processing per waterbody quantiles for the tsm variable
2026-03-13 20:22:57,602 __main__ [INFO]: Processing per waterbody quantiles for the st_max variable
2026-03-13 20:24:07,666 __main__ [INFO]: Processing per waterbody quantiles for the st_median variable
2026-03-13 20:25:17,259 __main__ [INFO]: Processing per waterbody quantiles for the st_min variable

In [30]:
per_waterbody_summaries = pd.concat(
    [*quantiles_df_to_merge, fai_cover_df, ndvi_cover_df], axis=1
)
per_waterbody_summaries = (
    per_waterbody_summaries.reset_index().rename(
        columns={"group": "wb_id"}
    )
)

per_waterbody_summaries["uid"] = per_waterbody_summaries[
    "wb_id"
].map(wb_id_to_uid_filtered)

per_waterbody_summaries["obs_id"] = (
    per_waterbody_summaries["time"].dt.strftime("%Y/%m/%d")
    + "_"
    + per_waterbody_summaries["uid"]
)

per_waterbody_summaries = per_waterbody_summaries.rename(
    columns={"time": "date"}
)
cols = per_waterbody_summaries.columns.tolist()
cols.insert(0, cols.pop(cols.index("uid")))
cols.insert(0, cols.pop(cols.index("obs_id")))

per_waterbody_summaries = per_waterbody_summaries[cols].drop(
    columns=["wb_id"]
)
per_waterbody_summaries

,obs_id,uid,date,hue_q0_1,hue_q0_2,hue_q0_3,hue_q0_4,hue_q0_5,hue_q0_6,hue_q0_7,...,st_min_q0_2,st_min_q0_3,st_min_q0_4,st_min_q0_5,st_min_q0_6,st_min_q0_7,st_min_q0_8,st_min_q0_9,fai_cover,ndvi_cover
0,2000/07/01_kxv7txxgy2,kxv7txxgy2,2000-07-01 23:59:59.999999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2000/07/01_kxvkvdcwb9,kxvkvdcwb9,2000-07-01 23:59:59.999999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2000/07/01_kxvmqfpr2g,kxvmqfpr2g,2000-07-01 23:59:59.999999,65.075523,68.414290,70.306278,71.614049,72.541687,73.329263,73.961272,...,24.258887,24.335111,24.463787,24.591014,24.719041,24.913462,25.292544,25.862793,15.718157,100.0
3,2000/07/01_kxvnpqqgnb,kxvnpqqgnb,2000-07-01 23:59:59.999999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2000/07/01_kxvppeum9d,kxvppeum9d,2000-07-01 23:59:59.999999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2270,2024/07/01_kxvz3bmur9,kxvz3bmur9,2024-07-01 23:59:59.999999,52.747874,54.442206,55.547493,56.523738,57.331818,58.360995,59.490118,...,27.717723,27.804502,27.841443,27.942921,28.007575,28.097629,28.188004,28.359895,4.040404,100.0
2271,2024/07/01_kxvz90p9qc,kxvz90p9qc,2024-07-01 23:59:59.999999,51.521418,52.260491,53.205862,53.977848,54.642681,55.206715,55.874445,...,24.626146,24.804581,24.956333,25.104448,25.304451,25.510977,25.755476,26.136326,24.521073,100.0
2272,2024/07/01_kxvz9pkd6v,kxvz9pkd6v,2024-07-01 23:59:59.999999,50.606647,50.913123,51.086071,51.499561,51.850805,52.239749,52.444054,...,28.674466,28.899093,29.078790,29.177456,29.299467,29.400494,29.490704,29.606368,46.666667,100.0
2273,2024/07/01_kxvzk8pdhp,kxvzk8pdhp,2024-07-01 23:59:59.999999,57.063499,57.836127,59.352818,152.954459,169.359146,177.449667,179.862949,...,24.194794,24.230059,24.725130,25.571819,25.826429,26.104671,27.287075,28.227490,31.746032,100.0
2274,2024/07/01_kxvzum71e6,kxvzum71e6,2024-07-01 23:59:59.999999,49.592639,50.281147,50.628098,50.899206,51.347773,51.682270,52.748974,...,23.002051,23.070634,23.104589,23.137722,23.177238,23.205224,23.232330,23.286890,37.777778,100.0

In [31]:
add_water_quality_observations_to_db(
    water_quality_measures=per_waterbody_summaries,
    engine=engine,
    update_rows=overwrite,
)

2026-03-13 20:27:34,263 water_quality.summaries.summary [INFO]: Found 1638 out of 2275 waterbody observations already in the waterbodies_water_quality table
2026-03-13 20:27:35,867 water_quality.summaries.summary [INFO]: Updating 1638 water quality observations in the waterbodies_water_quality table
2026-03-13 20:27:37,454 water_quality.summaries.summary [INFO]: Inserting 637 water quality observations in the waterbodies_water_quality table

In [32]:
results = pd.read_sql("SELECT * FROM waterbodies_water_quality", con=engine )
results

,obs_id,uid,date,hue_q0_1,hue_q0_2,hue_q0_3,hue_q0_4,hue_q0_5,hue_q0_6,hue_q0_7,...,st_min_q0_2,st_min_q0_3,st_min_q0_4,st_min_q0_5,st_min_q0_6,st_min_q0_7,st_min_q0_8,st_min_q0_9,fai_cover,ndvi_cover
0,2007/07/02_kxv7txxgy2,kxv7txxgy2,2007-07-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2007/07/02_kxvkvdcwb9,kxvkvdcwb9,2007-07-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2007/07/02_kxvmqfpr2g,kxvmqfpr2g,2007-07-02,64.113471,65.6211,66.717152,67.866568,69.088661,70.07392,71.233648,...,23.640678,23.755594,23.833941,23.914207,23.981078,24.092568,24.315033,24.723758,20.481928,100.0
3,2007/07/02_kxvnpqqgnb,kxvnpqqgnb,2007-07-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2007/07/02_kxvppeum9d,kxvppeum9d,2007-07-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2270,2006/07/02_kxvz3bmur9,kxvz3bmur9,2006-07-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2271,2006/07/02_kxvz90p9qc,kxvz90p9qc,2006-07-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15.327445,15.497772,15.638831,15.818607,15.989104,16.083138,16.329385,16.829510,100.000000,100.0
2272,2006/07/02_kxvz9pkd6v,kxvz9pkd6v,2006-07-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2273,2006/07/02_kxvzk8pdhp,kxvzk8pdhp,2006-07-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,17.487070,17.500286,17.520840,17.551329,17.596674,17.619368,17.670775,17.916419,100.000000,100.0
2274,2006/07/02_kxvzum71e6,kxvzum71e6,2006-07-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,21.562263,21.680324,21.741023,21.771427,21.819637,21.852525,22.497078,23.608628,97.777778,100.0